<!DOCTYPE html><html lang="en" ><head ><title >Catch?</title><meta name='viewport' content='width=device-width, initial-scale=0.66'><meta name='description' content='language:basic, target:desktop, category:game development'><link rel="styleSheet" href="../skins/granite/style.css" type="text/css"><style type="text/css">div.bbcode {padding: 8px;background: #E5E5E5;color: #000000;border: 1px dashed #B4B4BE;}</style></head><body ><table width=100% cellspacing=0 cellpadding=0><tr ><td class="menubarleft"></td><td class="menubar"><table cellspacing="0" cellpadding="0"><tr ><td >&nbsp;</td><td class="menuitemleft"></td><td class="menuitem"><a href="/" class="menuitem">News</a></td><td class="menuitemright"></td><td class="menuitemleft"></td><td class="menuitem"><a href="/forums.php" class="menuitem">Forums</a></td><td class="menuitemright"></td><td class="menuitemleft"></td><td class="menuitem"><a href="/codearcs.php" class="menuitem">Code</a></td><td class="menuitemright"></td><td class="menuitemleft"></td><td class="menuitem"><a href="/logs.php" class="menuitem">Logs</a></td><td class="menuitemright"></td><td class="menuitemleft"></td><td class="menuitem"><a href="/gallery.php" class="menuitem">Gallery</a></td><td class="menuitemright"></td><td class="menuitemleft"></td><td class="menuitem"><a href="/sdkspecs.php" class="menuitem">Specs</a></td><td class="menuitemright"></td><td class="menuitemleft"></td><td class="menuitem"><a href="/search.php" class="menuitem">Search</a></td><td class="menuitemright"></td></tr></table></td><td class="menubarright"></td></tr></table><div class="main"><h1 >Catch?</h1><a href="forums.php" >BlitzMax Forums</a>/<a href="topics.php?forum=101" >BlitzMax Beginners Area</a>/<a href="#bottom" >Catch?</a><br><br>
<a name="725269"></a>
<table width=100% cellspacing=0 cellpadding=0><tr ><td class="posthead"><table width=100% cellspacing=0 cellpadding=0><tr ><td >doswelk</td><td align="right"><font class=tiny>(Posted 2006)</font>&nbsp;<a href="#1">[#1]</a></td></tr></table></td></tr><tr ><td class="posttext"> Local aValue$[] = ["Simon" , "Dave"]<br><br>Print "array length=" + Len(avalue)<br><br>Try<br><br>	Print avalue[0]<br>	Print avalue[1]<br>	Print avalue[2]<br><br>Catch a$<br><br>	Print a$<br><br>EndTry<br><br>Above is some sample code, why doesn't catch catch the error?<br><br>The example in the help seems to imply that catch will only catch an exception you throw yourself? <br><br></td></tr></table><br>
<a name="725272"></a>
<table width=100% cellspacing=0 cellpadding=0><tr ><td class="posthead"><table width=100% cellspacing=0 cellpadding=0><tr ><td >Yan</td><td align="right"><font class=tiny>(Posted 2006)</font>&nbsp;<a href="#2">[#2]</a></td></tr></table></td></tr><tr ><td class="posttext"> <pre class=code>Local aValue$[] = ["Simon" , "Dave"]

Print "array length=" + Len(avalue)

Try
	Print avalue[0]
	Print avalue[1]
	Print avalue[2]
Catch exception:Object
	Print exception.ToString()
EndTry</pre> <br><br></td></tr></table><br>
<a name="725273"></a>
<table width=100% cellspacing=0 cellpadding=0><tr ><td class="posthead"><table width=100% cellspacing=0 cellpadding=0><tr ><td >doswelk</td><td align="right"><font class=tiny>(Posted 2006)</font>&nbsp;<a href="#3">[#3]</a></td></tr></table></td></tr><tr ><td class="posttext"> Thanks yan<br><br>That's more like what I was expecting, the more I look at the examples in the help files the less help i seem to get!<br><br>How do you get the code window? <br><br></td></tr></table><br>
<a name="725283"></a>
<table width=100% cellspacing=0 cellpadding=0><tr ><td class="posthead"><table width=100% cellspacing=0 cellpadding=0><tr ><td >Yan</td><td align="right"><font class=tiny>(Posted 2006)</font>&nbsp;<a href="#4">[#4]</a></td></tr></table></td></tr><tr ><td class="posttext"> Yeah, the try/catch command examples are a bit misleading. :o/<br><br>Have a look at 'Language&gt;Exceptions', it's much more helpful.<br><br><b><u><a href="/faq/faq_entry.php?id=2" >What are the forum codes?</a></u></b> <br><br></td></tr></table><br>
<a name="725292"></a>
<table width=100% cellspacing=0 cellpadding=0><tr ><td class="posthead"><table width=100% cellspacing=0 cellpadding=0><tr ><td >ImaginaryHuman</td><td align="right"><font class=tiny>(Posted 2006)</font>&nbsp;<a href="#5">[#5]</a></td></tr></table></td></tr><tr ><td class="posttext"> I use the code you use, with Catch A$ and print A$, seems to trap opengl errors okay.<br><br>Also did you get a catch when compiling with debug on? <br><br></td></tr></table><br>
<a name="725333"></a>
<table width=100% cellspacing=0 cellpadding=0><tr ><td class="posthead"><table width=100% cellspacing=0 cellpadding=0><tr ><td >Azathoth</td><td align="right"><font class=tiny>(Posted 2006)</font>&nbsp;<a href="#6">[#6]</a></td></tr></table></td></tr><tr ><td class="posttext"> Catch A$ won't trap anything other than strings being thrown, so it will fail on most exceptions. <br><br></td></tr></table><br>
<a name="725552"></a>
<table width=100% cellspacing=0 cellpadding=0><tr ><td class="posthead"><table width=100% cellspacing=0 cellpadding=0><tr ><td >Grey Alien</td><td align="right"><font class=tiny>(Posted 2006)</font>&nbsp;<a href="#7">[#7]</a></td></tr></table></td></tr><tr ><td class="posttext"> Try this code from my framework (you may need to modify it):<br><br><pre class=code>
Function HandleGeneralError(o:Object)
	'This should be called inside the Catch section of a Try/Catch/End Try like this:
	'Try
	'  'some code
	'Catch o:Object
	'  HandleGeneralError(o)
	'  Shutdown()
	'End Try
	
	EndGraphics 'safety to ensure desktop isn't messed up
	ShowMouse() 'make sure user can click on dialog.
	
	'In debug mode, this will display a valid error message.
	'In non-debug mode (final release), this will show a dialog saying "memory execption error"
	'which is better than nothing.
	'In full-screen mode, this will still show a dialog on the desktop after the graphics mode
	'is ended, and when the dialog is clicked, the game will shutdown.
	If TBlitzException(o) Then
		Local Prefix$ = ""
		If DebugInt&lt;&gt; 0 Then Prefix = "("+DebugInt+") "
		Notify Prefix + TBlitzException(o).ToString()
	Else
		'Perhaps a string has been raised? If so, show it.
		Notify o.Tostring()
	EndIf
End Function
</pre> <br><br></td></tr></table><br>
<a name="725575"></a>
<table width=100% cellspacing=0 cellpadding=0><tr ><td class="posthead"><table width=100% cellspacing=0 cellpadding=0><tr ><td >Azathoth</td><td align="right"><font class=tiny>(Posted 2006)</font>&nbsp;<a href="#8">[#8]</a></td></tr></table></td></tr><tr ><td class="posttext"> You can have multiple catch blocks:<br><br><pre class=code>Try 
	...
Catch a$
	...
Catch Ex:TBlitzException
	...
Catch b:Object
	...
EndTry
</pre> <br><br></td></tr></table><br>
<a name="725595"></a>
<table width=100% cellspacing=0 cellpadding=0><tr ><td class="posthead"><table width=100% cellspacing=0 cellpadding=0><tr ><td >Dubious Drewski</td><td align="right"><font class=tiny>(Posted 2006)</font>&nbsp;<a href="#9">[#9]</a></td></tr></table></td></tr><tr ><td class="posttext"> Man, I've read the Blitz documentation, I've read these posts, I've programmed for a decade now <br>... but I still have no idea what Try and Catch do. <br><br></td></tr></table><br>
<a name="725613"></a>
<table width=100% cellspacing=0 cellpadding=0><tr ><td class="posthead"><table width=100% cellspacing=0 cellpadding=0><tr ><td >Perturbatio</td><td align="right"><font class=tiny>(Posted 2006)</font>&nbsp;<a href="#10">[#10]</a></td></tr></table></td></tr><tr ><td class="posttext"> <div class="quote"> I still have no idea what Try and Catch do.  <br></div><br>If an error occurs inside the try..catch block, BMax throws an exception (which catch captures), you can then handle the error between the Catch and End Try block. <br><br></td></tr></table><br>
<a name="725656"></a>
<table width=100% cellspacing=0 cellpadding=0><tr ><td class="posthead"><table width=100% cellspacing=0 cellpadding=0><tr ><td >ImaginaryHuman</td><td align="right"><font class=tiny>(Posted 2006)</font>&nbsp;<a href="#11">[#11]</a></td></tr></table></td></tr><tr ><td class="posttext"> Hmm that's good to know, I didn't know I was only catching strings. Thanks. <br><br></td></tr></table><br>
<a name="726722"></a>
<table width=100% cellspacing=0 cellpadding=0><tr ><td class="posthead"><table width=100% cellspacing=0 cellpadding=0><tr ><td >doswelk</td><td align="right"><font class=tiny>(Posted 2006)</font>&nbsp;<a href="#12">[#12]</a></td></tr></table></td></tr><tr ><td class="posttext"> Ok; I understand the Try-Catch a bit better now, but...<br><br>Even with the code posted by "yan" or "Grey alien", the catch statement still does not catch the error in the code I posted.<br><br><pre class=code>
Local aValue$[] = ["Simon" , "Dave"]

Print "array length=" + Len(avalue)

Try
	Print avalue[0]
	Print avalue[1]
	Print avalue[2]
Catch o:Object
	Print o.ToString()
EndTry
</pre><br><br>This still fails with a nasty application error "Attempt to index array element beyond array length". <br><br></td></tr></table><br>
<a name="726728"></a>
<table width=100% cellspacing=0 cellpadding=0><tr ><td class="posthead"><table width=100% cellspacing=0 cellpadding=0><tr ><td >Azathoth</td><td align="right"><font class=tiny>(Posted 2006)</font>&nbsp;<a href="#13">[#13]</a></td></tr></table></td></tr><tr ><td class="posttext"> It works if debug is on, maybe release mode doesn't generate the checking code? <br><br></td></tr></table><br>
<a name="726745"></a>
<table width=100% cellspacing=0 cellpadding=0><tr ><td class="posthead"><table width=100% cellspacing=0 cellpadding=0><tr ><td >Perturbatio</td><td align="right"><font class=tiny>(Posted 2006)</font>&nbsp;<a href="#14">[#14]</a></td></tr></table></td></tr><tr ><td class="posttext"> Try-Catch is a debug only thing (would be nice if it weren't), the docs should really be updated to reflect this. <br><br></td></tr></table><br>
<a name="726747"></a>
<table width=100% cellspacing=0 cellpadding=0><tr ><td class="posthead"><table width=100% cellspacing=0 cellpadding=0><tr ><td >Dreamora</td><td align="right"><font class=tiny>(Posted 2006)</font>&nbsp;<a href="#15">[#15]</a></td></tr></table></td></tr><tr ><td class="posttext"> That would make it totally useless as Try Catch is meant to give usefull error message if it fails in release mode?!<br><br>The problem with above examples: The Array out of bound check etc are only performed during Debug so they actually can not fire anything in release, they just break. <br><br></td></tr></table><br>
<a name="771417"></a>
<table width=100% cellspacing=0 cellpadding=0><tr ><td class="posthead"><table width=100% cellspacing=0 cellpadding=0><tr ><td >watusimoto</td><td align="right"><font class=tiny>(Posted 2007)</font>&nbsp;<a href="#16">[#16]</a></td></tr></table></td></tr><tr ><td class="posttext"> To Perturbatio:  It appears that Try-Catch does work with both debug and release versions of BlitzMax programs.  However, I believe the reason that doswelk's code broke during release version was that array bounds checking is disabled -- therefore no exception was thrown.  If it had been thrown, I believe it would have been caught as expected. <br><br></td></tr></table><br>
<a name="771452"></a>
<table width=100% cellspacing=0 cellpadding=0><tr ><td class="posthead"><table width=100% cellspacing=0 cellpadding=0><tr ><td >H&amp;K</td><td align="right"><font class=tiny>(Posted 2007)</font>&nbsp;<a href="#17">[#17]</a></td></tr></table></td></tr><tr ><td class="posttext"> Five Months, just to say exactly what the pevious post said ;)<br>Mind you Try-catch does need some more examples in the docs. <br><br></td></tr></table><br>
<a name="771707"></a>
<table width=100% cellspacing=0 cellpadding=0><tr ><td class="posthead"><table width=100% cellspacing=0 cellpadding=0><tr ><td >watusimoto</td><td align="right"><font class=tiny>(Posted 2007)</font>&nbsp;<a href="#18">[#18]</a></td></tr></table></td></tr><tr ><td class="posttext"> I think slowly ;-).  When I read the thread I was left with the impression that Try-Catch was only debug mode, which is incorrect.  I wanted to make it clear to subsequent readers that it works with release versions as well.  But yes, after I posted, I realized that the array explanation had been pointed out by Dreamora.  And I agree: more examples are needed, as well as examples of creating custom exception objects.  So, here's one:<br><br><pre class=code>
Type  invalidValueException Extends TBlitzException

	field msg:string = null

	Method toString:String()
		if msg then return msg else return "Invalid value!"
	End Method
End Type
</pre><br><br>And it's thrown like this:<br><br><pre class=code>
function strToBool:byte(s:string)
	
	select s.toLower().trim()	
		case "true"
			return True
		case "false"
			return False
		default
			local e:invalidValueException = new invalidValueException
			e.msg = "Bad value passed: " + s
			Throw e 
	end select

end function
</pre><br><br>and caught like this:<br><br><pre class=code>
try 
	b = strToBool(s)

catch ex:invalidValueException
	print ex.toString()
	' Do some error recovery things here

catch ex:object		' Catch other exceptions
	print ex.toString()
	' Do some other things here
end try
</pre> <br><br></td></tr></table><br>
<a name="bottom"></a>
<table width=100% cellspacing=0 cellpadding=0><tr ><td align="right"><a href="http://monkeycoder.co.nz" target="_blank"><img src="/img/monkey2.svg" ></a> <a href="https://github.com/blitz-research" target="_blank"><img src="/img/github.svg" ></a> <a href="https://discord.gg/qJccbSp" target="_blank"><img src="/img/discord.svg" ></a></td></tr></table><br></div><br><table width="100%"><tr><td></body></html lang="en">
